name: MoodTownMenu

version: 1.0

main: fr.moodcraft.townmenu.Main

api-version: '1.21'

authors:
  - MoodCraft

depend:
  - Towny
  - MoodTownFlag

commands:

  menuville:
    description: Menu ville MoodCraft
    aliases:
      - villemenu
      - townmenu
      - tm