name: MoodTownSuite
version: 1.0
main: fr.moodcraft.tgrade.Main
api-version: '1.21'
author: MoodCraft

depend:
  - Towny

commands:

  urbanisme:
    description: Commission urbaine MoodCraft
    usage: /urbanisme
    aliases:
      - tgrade
      - commission
      - urbain
      - mairie
      - projet
      - projets
      - tprojet
      - tprojets
      - vprojet
      - vprojets

  urbanismeadmin:
    description: Administration de la commission urbaine MoodCraft
    usage: /urbanismeadmin
    permission: moodtowngrade.admin
    aliases:
      - urbadmin
      - tgradeadmin
      - villeadmin

  topville:
    description: Classement national des villes
    usage: /topville

  vprojetsreset:
    description: Reset national des projets urbains
    usage: /vprojetsreset
    aliases:
      - vpr
      - villeprojetsreset
      - resetprojets
    permission: moodtowngrade.staff

  menuville:
    description: Menu ville MoodCraft
    usage: /menuville
    aliases:
      - villemenu
      - townmenu
      - tm

  pubville:
    description: Publicités de villes MoodCraft
    usage: /pubville
    aliases:
      - publiciteville
      - pubvilles
      - villesponsorisee
      - villesponsorisees

  drapeau:
    description: Menu drapeau des villes et nations MoodCraft
    usage: /drapeau
    aliases:
      - flag

permissions:

  moodtowngrade.staff:
    default: op

  moodtowngrade.admin:
    default: op

  moodtownflag.admin:
    default: op

  moodtownsuite.pubville.admin:
    default: op

  moodtownsuite.pubville.acheter:
    default: true

  moodtownsuite.pubville.liste:
    default: true
