name: MoodTownFlag

version: 1.0

main: fr.moodcraft.flag.Main

api-version: '1.21'

depend:
  - Towny

commands:

  drapeau:
    aliases:
      - flag

permissions:

  moodtownflag.admin:
    default: op