name: MoodTownGrade

version: 1.0

main: fr.moodcraft.tgrade.Main

api-version: '1.21'

author: MoodCraft

depend:
  - Towny

softdepend:
  - MoodTownFlag

commands:

  urbanisme:
    description: Commission urbaine MoodCraft
    usage: /urbanisme
    aliases:
      - tgrade
      - commission
      - urbain
      - mairie
      - projet
      - projets
      - tprojet
      - tprojets
      - vprojet
      - vprojets

  urbanismeadmin:
    description: Administration de la commission urbaine MoodCraft
    usage: /urbanismeadmin
    permission: moodtowngrade.admin
    aliases:
      - urbadmin
      - tgradeadmin
      - villeadmin

  topville:
    description: Classement national des villes
    usage: /topville

  vprojetsreset:
    description: Reset national des projets urbains
    aliases:
      - vpr
      - villeprojetsreset
      - resetprojets
    permission: moodtowngrade.staff

permissions:

  moodtowngrade.staff:
    default: op

  moodtowngrade.admin:
    default: op